config/routes.rb
Beeline::Application.routes.draw do

  devise_for :users

  get 'home' => 'pages#home'
  get 'home_old' => 'pages#home_old'
  get 'landing' => 'pages#landing'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'team' => 'pages#team'
  get 'map' => 'pages#map'
  get 'upload' => 'pages#upload'
  get 'all_brands' => 'pages#all_brands'
  get 'all_products' => 'pages#all_products'

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  resources :brands do
    resources :products
  end

  resources :products, only: [ :index, :show, :destroy, :edit ] do
    resources :secondary_images
  end

  namespace :admin do
    resources :users, only: [ :index, :update, :destroy ]
  end

  namespace :api do
    resources :registrations, only: [ :create ]
  end

  root :to => 'pages#home'

end

app/models/secondary_image.rb
class SecondaryImage < ActiveRecord::Base

  belongs_to :imageable, polymorphic: true

  validates_presence_of :image

  mount_uploader :image, ImageUploader
end

app/controllers/secondary_images_controller.rb
class SecondaryImagesController < ApplicationController

  before_action :require_admin

  def index
    @product = Product.find(params[:product_id])
    @images = SecondaryImage.where(imageable_id: params[:product_id], imageable_type: "Product")
    @image = @product.secondary_images.build
  end

  def create
    image = SecondaryImage.new(secondary_image_params)

    if image.save
      flash[:notice] = "Image added successfully."
    else
      flash[:error] = "Error saving the image. Try again."
    end

    redirect_to product_secondary_images_path(params[:product_id])
  end

  def destroy
    image = SecondaryImage.find(params[:id])

    if image.destroy
      flash[:notice] = "Image was removed."
    else
      flash[:error] = "Error removing."
    end

    redirect_to product_secondary_images_path(params[:product_id])
  end

  private

    def secondary_image_params
      params.require(:secondary_image).permit(:image, :imageable_id, :imageable_type)
    end

end

app/views/secondary_images/_form.html.erb
<div class="well">
  <%= form_for [@product, @image], :html => { :multipart => true } do |f| %>
    <%= f.hidden_field :imageable_type %>
    <%= f.hidden_field :imageable_id %>
    <p>
      <%= f.file_field :image %>
    </p>
    <br>
    <p><%= f.button :submit, class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/secondary_images/_secondary_image.html.erb
<li>
  <%= image_tag secondary_image.image.thumb, id: "img-preview" %>
  <%= form_for [@product, secondary_image], :method => :delete do |form| %>
  <hr style="margin:4px; border-color:rgba(80,80,80,0.4)">
    <%= form.submit "DELETE", class: "btn btn-danger btn-xs centerize" %>
    <br>
  <% end %>
</li>

app/views/secondary_images/index.html.erb
<div class="col-md-offset-1 col-md-5 white-background">
  <br>
  <h6><%= link_to "Back to Product", edit_product_path(@product) %></h6>
  <hr>
  <div>
    <h4>Current Secondary Photos:</h4>
    <ul class="list-inline">
      <%= render @images %>
    </ul>
  </div>
    <h4>Upload another photo:</h4>
    <%= render 'form' %>
  </div>
</div>