config/routes.rb
Beeline::Application.routes.draw do

  devise_for :users

  get 'home' => 'pages#home'
  get 'home_old' => 'pages#home_old'
  get 'landing' => 'pages#landing'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'team' => 'pages#team'
  get 'map' => 'pages#map'
  get 'upload' => 'pages#upload'
  get 'all_brands' => 'pages#all_brands'
  get 'all_products' => 'pages#all_products'

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  resources :brands do
    resources :products
  end

  resources :products, only: [ :index, :show, :destroy, :edit ] do
    resources :secondary_images
  end

  namespace :admin do
    resources :users, only: [ :index, :update, :destroy ]
  end

  namespace :api do
    resources :registrations, only: [ :create ]
  end

  root :to => 'pages#home'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  validates :name, presence: true
  validates :profile, presence: true

  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :products, :dependent => :destroy

  has_one :profile_image, as: :imageable, :class_name => 'SecondaryImage'
  accepts_nested_attributes_for :profile_image, allow_destroy: true, :reject_if => lambda {|a| a['image'].blank?}

  mount_uploader :logo, ImageUploader

  def self.active_brands
    where(active: true)
  end

  def to_param
  	"#{id}-#{name.try(:parameterize)}"
  end

# Vanity URL: http://blog.teamtreehouse.com/creating-vanity-urls-in-rails


end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :require_admin, except: [ :show ]

  def index
    @brands = Brand.order("active desc, name ASC").page(params[:page]).per(100)
    @products = Product.order("created_at desc")

  end

  def show
    @brand = Brand.find(params[:id])
    # @products = Product.order("created_at ASC") < Doesnt do anything.
    @brands = Brand.active_brands.order("RANDOM()").limit(4)
  end

  def new
    @brand = Brand.new
    @brand.build_profile_image
  end

  def create
    @brand = Brand.new(brand_params)
    @brand.owner = current_user

    if @brand.save
      redirect_to @brand
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])

    if @brand.update(brand_params)
      redirect_to @brand
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end

  private

    # TODO may be missing something here to set owner_id
    def brand_params
      params.require(:brand).permit(:name, :profile, :city, :state, :zip, :street, :untappd, :ratebeer, :beeradvocate, :owner, :founders, :main_contact, :current_notes, 
                                    :facebook, :twitter, :instagram, :tumblr, :vid_vimeo, :vid_youtube, :public_information,
                                    :home_page, :active, :logo,
                                    profile_image_attributes: [ :image ])
    end

end

app/views/brands/_brand.html.erb
<div class="<%= size %>">
  	<%= link_to image_tag(brand.logo), brand_path(brand),class: 'thumbnail' %>
  	<!-- <h6 class="centerize" style="font-size:.6em !important;pointer-events:none;font-weight:600;letter-spacing:.05em !important;margin-top:-18px;padding-bottom:10px"><%#= brand.name%></h6> -->
</div>

app/views/brands/_form.html.erb
<%= form_for(@brand, html: { multipart: true, class: "form-horizontal" }) do |f| %>
  <div class="col-md-12 white-background" >
    <div class="row">
      <div class="form-actions" style="padding:10px;">
        <%= f.submit class: "btn btn-primary" %>
      </div>
      <div class="col-md-5 forms-admin">
        <%#= brand.error_notification %>
        <br>
        <span class="label label-warning">Active?</span>
        <%= f.check_box :active %>
        <br>
        <br>

        <span class="label label-success">Public?</span>
        <%= f.text_field :public_information, placeholder: "Taproom / Not Open to Public", label:false; %>

        <%= f.text_field :name, placeholder: "Brand Name", label:false;  %>
        <br>
        <%= f.text_field :street, placeholder: "Street", label:false; %>
        <%= f.text_field :city, placeholder: "City", label:false; %>
        <%= f.text_field :state, placeholder: "State", label:false; %>
        <%= f.text_field :zip, placeholder: "Zip Code", label:false; %>
                
        <%= f.text_field :founders, placeholder: "Founder's First Name(s)?", label:false; %>

        <br>
        <br>
        <h6>Social:</h6>
        <p>
          home:<%= f.text_field :home_page,label:'home', placeholder: "Home URL (brand.com)" %>
          fb:<%= f.text_field :facebook, placeholder: "facebook.com/_____" %>
          twtr:<%= f.text_field :twitter, placeholder: "twitter.com/_____" %>
          ig:<%= f.text_field :instagram, placeholder: "instagram.com/_____" %>
          tmblr:<%= f.text_field :tumblr, placeholder: "_____.tumblr.com/" %>
          vimeo:<%= f.text_field :vid_vimeo, placeholder: "Video ID" %>
          youtube:<%= f.text_field :vid_youtube, placeholder: "Video ID" %>
          untappd:<%= f.text_field :untappd, placeholder: "untappd.com/_________" %>
          ratebeer:<%= f.text_field :ratebeer, placeholder: "ratebeer.com/brewers/____/____" %>
          beeradvocate:<%= f.text_field :beeradvocate, placeholder: "beeradvocate.com/beer/profile/______/" %>
        </p>
      </div>
      <div class="col-md-7">
        <div class="row">
          <div class="col-md-6">
            <br>
            <h6>Logo:</h6>
            <p style="margin-top:-10px;font-size:.85em">(Logo on White Background or Map of Business >600x600)</p>
            <div id="preview">
              <% if @brand.logo? %>
                <p>Logo Preview: (upload a new picture to replace)</p>
                <%= image_tag @brand.logo, id: "img-preview" %>
              <% end %>
              <%= f.file_field :logo %>
            </div>
          </div>
          <div class="col-md-6">
            <br>
            <h6>Profile Image:</h6>
            <p style="margin-top:-10px;font-size:.85em">(Shop, Product Detail, or Founders)</p>
            <% if @brand.profile_image.persisted? %>
              <p>Image Preview: (upload a new picture to replace)</p>
              <%= image_tag @brand.profile_image.image, id: "img-preview" %>
            <% end %>
            <%= f.fields_for :profile_image do |image_field| %>
              <%= image_field.file_field :image %>
            <% end %>
          </div>
        </div>
        <hr>
        <h6>Brand Profile:</h6>
        <%= f.text_area :profile, as: :text, :rows => "10", :cols => "50", class: 'wysihtml5 textbox', label: false;%>
        <hr>
        <div class="forms-admin">
          <h6>Brewery Contacts:</h6>
          Main Contact:<%= f.text_field :main_contact,label:'home', placeholder: "Name, founder@brand.com, 000-000-0000" %>
        </div>
        <h6>Notes:</h6>
        <%= f.text_area :current_notes, as: :text, :rows => "7", :cols => "50", class: 'wysihtml5 textbox', label: false;%>
      </div>
    </div>
  </div>
<% end %>

<% content_for(:scripts) do %>
  <script type="text/javascript">
    $(function() {
      $('.wysihtml5').each(function(i, elem) {
        $(elem).wysihtml5({"html": true, "color": true, "font-styles": false});
      });
    })
  </script>
<% end %>

app/views/brands/edit.html.erb
<div class="col-md-offset-1 col-md-9 white-background">
	<h1>Edit Brand</h1>
	<h6>
		<%= link_to 'Back', :back %> //
		<%= link_to 'Show', @brand %> //
		<%= link_to 'All', brands_path %>
	</h6>

    <%= render 'form' %>
</div>

app/views/brands/index.html.erb
<div class="col-md-offset-1 col-md-7 white-background">
<h1>Brand List</h1>
 <h5 style="font-size:.9em;">Total: <%= Brand.count%></h5>
<hr style="border-color: rgba(0,0,0,.3);margin-top:2px">
  <ul class="list-unstyled">
    <% @brands.each do |brand| %>
    <li>
        
        <ul class="list-inline">
          <li>
            <% if brand.active == true %>
              <span class="glyphicon glyphicon-ok" style="color:#389e39"></span>
            <% else %>
              <span class="glyphicon glyphicon-remove" style="color:#A32638"></span>
            <% end %>
            <h6 style="display: inline;font-size:.8em !important;font-weight:500;"><%= link_to brand.name, edit_brand_path(brand) %></h6>
          </li>
          <li style="border-left:1px solid rgba(80,80,80,.5);border-right:1px solid rgba(80,80,80,.5);margin-right:3px;">
            <%= image_tag(brand.logo, size: "30x30") %>
            <%= image_tag(brand.profile_image.image, height:"30") %>
          </li>
          <br>
      	<% brand.products.each do |product| %>
          <%# if product.primary_image.url %>
            <!-- <li><%#= link_to image_tag(product.primary_image, size: "30x30"), edit_brand_product_path(brand, product)%></li>
          <%# else %> -->
            <li style="font-size:.65em;"><%= link_to product.name, edit_brand_product_path(brand, product) %></li>
            <li>|</li>
          <%# end %>
      	<% end %>
      	<li>
          <div id="add-product"><%= link_to "+", new_brand_product_path(brand)%></div>
        </li>
      </ul>
      <br>
    </li>
    <li>
      <hr style="margin:-10px;border-color:#505050;opacity:.2;">
    </li>
    <br>
    <% end %>
  </ul>
  <%= paginate @brands %>
</div>

app/views/brands/new.html.erb
<div class="col-md-offset-1 col-md-9 white-background">
	<h1>Add Brand</h1>
    <%= render 'form' %>
</div>

app/views/brands/show.html.erb
<div class="col-md-6" id="b-midpane" style="margin-right:1px !important">
  <div class="row">
    <div class="col-md-12">
      <div style="margin-top:-20px;margin-bottom:20px">
        <a href="/" class="backhome-btn" style="margin-top:-15px"><div class="glyphicon glyphicon-globe" ></div></a>
        <a class="visible-xs visible-sm pull-right" style="padding-right:15px;margin-top:5px" href="mailto:?subject=Take a look at Farallon Co...&amp;body=You should check out <%= @brand.name %> on Farallon Co.: <%=request.original_url.html_safe%>" ><%= image_tag("email-message.png", class: "social-show", width: "25") %></a>
      </div>
        <div class="row">
          <div class="col-md-12">
          <div class="centerize hidden-xs hidden-sm">
            <h5 id="social-title" style="margin-top:0px;letter-spacing:2px;font-size:.65em" class="centerize" >SPREAD THE WORD</h5>
                <!-- TWITTER -->
              <a href="http://twitter.com/home?status=Check+out+@<%= @brand.twitter %>+found+on+@farallonco+(<%=request.original_url.html_safe%>)" target="blank" ><%= image_tag("twitter.png", id:"fb-social", class: "social-show", width: "25") %>
              </a>
              <!-- FACEBOOK -->
              <a href="http://www.facebook.com/sharer/sharer.php?s=100&p[url]=<%=request.original_url%>&p[images][0]=<%= @brand.logo.url %>&p[title]=Check+out+<%= @brand.name %>&p[summary]=Farallon+Co.+-+Find+the+Best+Brands,+Submit+Product+Ideas+,+Join+the+Company." target="blank"><%= image_tag("facebook.png", class: "social-show", width: "20") %></a>
              <!-- TUMBLR -->
              <a href="http://www.tumblr.com/share/photo?source=<%=u @brand.logo.url %>&caption=<%=u @brand.name %>+found+on+Farallon+Co.&clickthru=<%=u request.original_url %>" target="blank" ><%= image_tag("tumblr.png", class: "social-show", width: "20") %>
              </a>
              <a href="mailto:?subject=Take a look at Farallon Co...&amp;body=You should check out <%= @brand.name %> found on Farallon Co.: <%=request.original_url.html_safe%>" ><%= image_tag("email-message.png", class: "social-show", width: "20") %></a>
              
              <hr class="black-hr" style="width:50%">
          </div>
        </div>
      </div>
  </div>
</div>
  

  <!-- PROFILE -->
  <div class="row">
    <div class="col-md-12">
      <%= image_tag(@brand.logo, id: "brand-logo-preview") %>
      <h6 style="margin-bottom:-15px">MEET THE BREWERY:</h6>
      <h3><%=@brand.name.html_safe%></h3>
      <h5 class="location" style="font-size:.85em;letter-spacing:1px;" ><%=@brand.city.html_safe%>,&nbsp;<%=@brand.state.html_safe%></h5>

    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <% if @brand.vid_vimeo.blank? && @brand.vid_youtube.blank? %>
        <%= image_tag(@brand.profile_image.image, id: "brand-image") %>
      <% else %>
        <% if @brand.vid_youtube.blank? %>
          <iframe class="centerize" style="padding-bottom:10px;" src="//player.vimeo.com/video/<%= @brand.vid_vimeo.html_safe %>?title=0&amp;byline=0&amp;portrait=0" width="100%" height="350" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

        <% else %>
          <iframe class="centerize" style="padding-bottom:10px;" width="100%" height="350" src="//www.youtube.com/embed/<%= @brand.vid_youtube.html_safe %>?rel=0" frameborder="0" allowfullscreen></iframe>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row" >
    <div class="col-md-12">
      <p><%=@brand.profile.html_safe%></p>
      <hr class="black-hr">
        <div class="centerize">
            <h5 style="font-size:.85em;letter-spacing:1px;" ><span style="font-weight:900"><%=@brand.name.html_safe%></span><br><%=@brand.street.html_safe%><br><%=@brand.city.html_safe%>,&nbsp;<%=@brand.state.html_safe%>&nbsp;<%=@brand.zip%></h5>
              <hr style="margin-bottom:2px;width:20%;opacity:.6">
              <h6 style="font-size:.6em !important;pointer-events:none;"><%=@brand.public_information.html_safe%></h6>
              <hr style="margin-top:2px;width:20%;opacity:.6">

            <span id="social-places">PLACES TO VISIT:</span>
            <!-- HOME -->
            <% if @brand.home_page != "" %>
              <a href="http://www.<%= @brand.home_page %>" target="blank"><%= image_tag("home-square.png", class: "brandsocial") %></a>
            <% end %>
            <!-- FACEBOOK -->
            <% if @brand.facebook != "" %>
              <a href="https://facebook.com/<%= @brand.facebook %>" target="blank"><%= image_tag("facebook_square_black.png", class: "brandsocial") %></a>
            <% end %>
            <!-- TWITTER -->
            <% if @brand.twitter != "" %>
              <a href="http://twitter.com/<%= @brand.twitter %>" target="blank"><%= image_tag("twitter_square_black.png", class: "brandsocial") %></a>
            <% end %>
            <!-- INSTAGRAM -->
            <% if @brand.instagram != "" %>
              <a href="http://instagram.com/<%= @brand.instagram %>" target="blank"><%= image_tag("instagram_square_black.png", class: "brandsocial") %></a>
            <% end %>
            <!-- TUMBLR -->
            <% if @brand.tumblr != "" %>
              <a href="http://<%= @brand.tumblr %>.tumblr.com/" target="blank"><%= image_tag("tumblr_square_black.png", class: "brandsocial") %></a>
            <% end %>
            <!-- UNTAPPD -->
            <% if @brand.untappd != "" %>
              <a href="http://untappd.com/<%= @brand.untappd %>" target="blank"><%= image_tag("untappd_square_black.png", class: "brandsocial") %></a>
            <% end %>
            <!-- RATE BEER -->
            <% if @brand.ratebeer != "" %>
              <a href="http://ratebeer.com/brewers/<%= @brand.ratebeer %>" target="blank"><%= image_tag("ratebeer_square_black.png", class: "brandsocial") %></a>
            <% end %>
            <!-- BEER ADVOCATE -->
            <% if @brand.beeradvocate != "" %>
              <a href="http://beeradvocate.com/beer/profile/<%= @brand.beeradvocate %>" target="blank"><%= image_tag("beeradvocate_square_black.png", class: "brandsocial") %></a>
            <% end %>
      </div>
      <% if current_user.try(:admin?) %>
    <hr class="black-hr">
    <div class="centerize">
      <span style="font-size:.65em;"><%= link_to "X", @brand, class: 'x-btn', method: :delete, data: { confirm: 'Are you sure?' } %></span>&nbsp;/
      <span><%= link_to "EDIT", edit_brand_path%></span>&nbsp;/
      <span style="font-size:3em;font-weight:900;"><%= link_to "+", new_brand_product_path(@brand)%></span>
      
        <h6>Brand Contacts & Information:</h6>
        Main: <%= @brand.main_contact unless @brand.main_contact.blank? %>
        <br>
      </div>
      Notes:
        <%= @brand.current_notes unless @brand.current_notes.blank? %>
    <%end%>
    </div>
  </div>
</div>


<div class="col-md-3 product-grid grey-border" style="border-top-left-radius:0px;border-bottom-left-radius:0px;background-color:white;margin-bottom:100px;">

     <!--  <a href="/" class="links centerize"><h6 style="color:black !important;">BACK TO HOME</h6></a>
      <h5 style="padding-bottom:2px; color:black; pointer-events:none; letter-spacing:1px; font-size:1.1em;"class="centerize" >CURRENT PROJECTS</h5>
      <hr class="centerize" style="padding-bottom:10px; width:70%">
    </div>
  </div> -->
  <!-- <div class="row">

    <%# if @brand.products.where(:active => true, :existingline => false).count == 0 %> 
      
    <%# else %>
      <%# @brand.products.select { |p| p.active && !p.existingline }.each do |product| %>
        <div class="col-md-6 col-xs-6">
          <%#= link_to image_tag(product.primary_image), product_path(product), class: "thumbnail" %>
        </div>
      <%# end %>
    <%# end %>
  </div> -->
  <div class="row">
    <div class="col-md-12">
      <h5 style="padding-bottom:2px; color:black; letter-spacing:1px; font-size:1.1em;"class="centerize" >THE STAPLES</h5>
      <hr class="centerize" style="padding-bottom:10px; width:60%">
    </div>
  </div>
  <div class="row">
    <% @brand.products.select { |p| p.active }.each do |product| %>
      <div class="col-md-6 col-xs-6">
        <%= link_to image_tag(product.primary_image), product, class: "thumbnail" %>
        <%#= link_to image_tag(product.primary_image), product_path(product), class: "thumbnail" %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h5 style="padding-bottom:2px; margin-top:40px; color:black; letter-spacing:1px; font-size:1.1em;pointer-events:none;"class="centerize" >MORE BREWERIES</h5>
      <hr class="centerize" style="padding-bottom:10px; width:60%">
    </div>
  </div>
  <div class="row">
    <%= render :partial=>'brands/brand', :collection => @brands, :locals => {:size => 'col-md-6 col-xs-6'}  %>
  </div>
</div>
<!--   <meta property="st:image" content="<%#=image_tag(@brand.logo)%>">-->

<!-- B&B Modal -->
          <div class="modal fade" id="existing-modal-brand" tabindex="-1" role="dialog" aria-labelledby="Submit" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" style="font-size:3em;margin-top:-10px;" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h3 class="modal-title">About the 'Bread & Butter Series'</h3>
                </div>
                <div class="modal-body" >

                  <p style="text-align:center;">This set of products is part of our 'Bread & Butter' series, which highlights the products that made this brand what it is today or simply new products we think you should be aware of. <br><br>Keep in mind that these are not campaigns. We merely are striving to become your one-stop-shop for product discovery.<br><br><i>Enjoy.</i></p>
                  <br>
                </div>
              </div>
            </div>
          </div>