config/routes.rb
Beeline::Application.routes.draw do

  devise_for :users

  get 'home' => 'pages#home'
  get 'home_old' => 'pages#home_old'
  get 'landing' => 'pages#landing'
  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'team' => 'pages#team'
  get 'map' => 'pages#map'
  get 'upload' => 'pages#upload'
  get 'all_brands' => 'pages#all_brands'
  get 'all_products' => 'pages#all_products'

  get 'contact' => 'contact#new'
  post 'contact' => 'contact#create'

  resources :brands do
    resources :products
  end

  resources :products, only: [ :index, :show, :destroy, :edit ] do
    resources :secondary_images
  end

  namespace :admin do
    resources :users, only: [ :index, :update, :destroy ]
  end

  namespace :api do
    resources :registrations, only: [ :create ]
  end

  root :to => 'pages#home'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :brand
  belongs_to :owner, class_name: "User"

  has_many :secondary_images, as: :imageable
  has_one :remote_data
  accepts_nested_attributes_for :secondary_images, allow_destroy: true, :reject_if => lambda {|a| a['image'].blank?}
  accepts_nested_attributes_for :remote_data, allow_destroy: true

  validates :name, presence: true
  validates :brand, presence: true

  mount_uploader :primary_image, ImageUploader

  def self.active_campaigns
    where(active: true, archived: false, existingline: false)
  end

  def self.active_products
    where(active: true, archived: false, existingline: true)
  end

  def has_secondary_images?
    secondary_images.count > 0
  end

  def to_param
    "#{id}-#{name.try(:parameterize) }"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :require_admin, except: [ :show ]

  def index
    @products = Product.order("existingline, updated_at desc, created_at desc, active").page(params[:page]).per(250)
  end

  def show
    @product = Product.find(params[:id])
    @brand = @product.brand.id
    @products = Product.active_campaigns.order("RANDOM()").limit(6)
    # @products = Product.active_campaigns.order("updated_at desc").limit(6)
    @brands = Brand.active_brands.order("RANDOM()").limit(4)
  end

  def new
    @product = current_brand.products.build
    @product.build_remote_data
  end

  def edit
    @product = Product.find(params[:id])
    @product.build_remote_data unless @product.remote_data
  end

  def create
    @product = current_brand.products.new(product_params)
    @product.owner = current_user

    if @product.save
      redirect_to [current_brand, @product]
    else
      format.html { render action: "new" }
    end
  end

  # def clone
  #   @product = Product.find(params[:id]) 
  #   @product = Prescription.new(@product.attributes) 
  #   render :new 
  # end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [current_brand, @product], notice: 'Product was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
    end
  end

  private

    def current_brand
      @brand ||= Brand.find(params[:brand_id])
    end

    def product_params
      params.require(:product).
              permit( :name, :tasting_notes, :materials, :abv, :hops, :ibu, :style, :price,
                      :status, :active, :archived, :usa, :limited, :primary_image,
                      :existingline, :existingurl, :owner, :grain_bill,
                      secondary_images_attributes: [ :image ],
                      remote_data_attributes: [ :slug ],
                      brand_attributes: [ :name, :profile ] )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@product.brand, @product], html: { class: "form-horizontal" }) do |f| %>
<div class="col-md-12 white-background" >
  <div class="row">
    <div class="col-md-4">
      <%#= f.error_notification %>
        <div class="form-actions" style="padding:10px;">
          <%= f.submit class: "btn btn-primary" %>
        </div>

        <%= f.check_box :active %> Active?
        <br>
        <%= f.check_box :archived %> Archive?
        <br>

        <div class="forms-admin">
          <br>
          <%#= f.error_notification %>

          <%= f.text_field :name, placeholder: "Enter Product Name",label:false %>
          <%= f.text_field :price, placeholder: "Price ($, $$, $$$)",label:false %>
          <br>
          <%= f.text_field :status, placeholder: "Status?",label:false %>
          <%= f.text_field :abv, placeholder: "ABV (%)",label:false %>
          <%= f.text_field :ibu, placeholder: "IBU",label:false %>

          <br>
        </div>
        <div class="row">
            <div class="col-md-12">
              <h6>Existing Product Information:</h6>
                <%= f.check_box :existingline %> Enable?
                <%= f.text_field :existingurl, placeholder: "Product URL",label:false,class:'textbox' %>
                <hr style="border-color:black;">
              <br>
            </div>
          </div>
    </div>

    <div class="col-md-8">

      <%#= f.full_error :image_file_size, class: "alert alert-error" %>
      <%#= f.full_error :image_content_type, class: "alert alert-error" %>
      <div class="row">
        <div class="col-md-6">
          <h6>Primary Image:</h6><p style="margin-top:-10px; font-size:.85em">(Main Picture of Product >600x600)<p>
          <% if @product.primary_image? %>
            <p>Image Preview: (upload a new picture to replace)</p>
            <%= image_tag @product.primary_image, id: "img-preview" %>
          <% end %>
          <%= f.file_field :primary_image %>
        </div>
        <% if @product.persisted? %>
          <div class="col-md-6">
            <h6>Secondary Images:</h6><p style="margin-top:-10px; font-size:.85em">(Alternate Product Photos >600x600)<p>
            <h5 style="font-size:.7em"><%= link_to "Edit secondary photos", product_secondary_images_path(@product) %></h5>
            <% if @product.has_secondary_images? %>
              <h6>Current Photos:</h6>
              <% @product.secondary_images.each do |image| %>
                <%= image_tag image.image, id: "img-preview" %>
              <% end %>
            <% else %>
              <p>No Secondary Photos uploaded yet.</p>
            <% end %>
            
          </div>
        <% end %>
      </div>

      <hr style="border-color:black;">
      <div class="row">
        <div class="col-md-12">
          <h6>Details:</h6>
            <%= f.text_area :tasting_notes, as: :text, :rows => "8", :cols => "50", class: 'wysihtml5 textbox', placeholder: "Narrative about product", label:false;%>
         
          <div class="row">
            <div class="col-md-6">
              <h6>Grain Bill:</h6>
              <p style="font-size:.8em;">(i.e. 10"Wx12"H)</p>
              <%= f.text_area :grain_bill, as: :text, :rows => "6", :cols => "20", class: 'wysihtml5 textbox', label:false;%>
            </div>
            <div class="col-md-6">
              <h6>Hops:</h6>
              <%= f.text_area :hops, as: :text, :rows => "6", :cols => "20", class: 'wysihtml5 textbox', label:false;%>
            </div>
            
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<% end %>

<% content_for(:scripts) do %>
  <script type="text/javascript">
    $(function() {
      $('.wysihtml5').each(function(i, elem) {
        $(elem).wysihtml5({"html": true, "color": true, "font-styles": false});
      });
    })
  </script>
<% end %>

app/views/products/_product.html.erb
<div class="<%= size %>" >
	
  <%= link_to image_tag(product.primary_image), product_path(product), class: 'thumbnail', data: { product_id: product.id } %>

  <h6 style="position:absolute;bottom:14px;left:19px;text-align:left;pointer-events:none;color:white;opacity:0;font-size:.7em !important;padding:10px;background-color:rgba(0,0,0,0.6);border-top-right-radius:5px" class="tits">
		<span style="font-family:maven-pro, serif;font-size:1.6em;"><%= product.name%></span><hr style="margin:0;margin-bottom:-5px;opacity:.4;"><br>
		<span class="glyphicon glyphicon-signal" style="color:#3aa63b;font-size:1.9em;"></span>&nbsp;
	</h6>
</div>

app/views/products/edit.html.erb
<div class="col-md-offset-1 col-md-9 white-background" >
	<h1>Editing product</h1>
	<h6>
		<%= link_to 'Back', :back %> //
		<%= link_to 'Show', @product %> //
		<%= link_to 'All', products_path %>
	</h6>


	<%= render 'form' %>

</div>

app/views/products/index.html.erb
<div class="col-md-offset-1 col-md-8 white-background">
  <h1>Products List</h1>
  <h5 style="font-size:.9em;">Total: <%= Product.count%></h5>
  <hr style="border-color: rgba(0,0,0,.3);margin-top:2px">
  <div class="table-responsive">
    <table class="table table-striped table-condensed" style="font-size:.75em">
      <thead>
        <tr>
          <th>ID</th>
          <th>Active?</th>

          <th>Owner</th>
          <th>Brand</th>
          <th>Name</th>
          <th>Pic</th>
          <th>$</th>
          <th>Status</th>
          <th>Created</th>
          <th>Updated</th>
          
          <!-- <th>Update?</th> -->
          <th>Delete?</th>
        </tr>
      </thead>
      <tbody>

        <% @products.each do |product| %>

          <tr>
            <td><%= product.id %></td>
            <td><% if product.active == true %>
              <span class="glyphicon glyphicon-ok" style="color:#389e39"></span>
                <% else %>
              <span class="glyphicon glyphicon-remove" style="color:#A32638"></span>
              <% end %>
            </td>
            <td><%= product.owner_id %></td>
            <td><%= product.brand_id %></td>
            <td><%= link_to product.name, product %></td>
            <td><%= link_to image_tag(product.primary_image.thumb, size: "30x30"), product %></td>
            <td><%= product.price %></td>
            <td><%= product.status %></td>
            <td><%= product.created_at.strftime("%D") %></td>
            <td><%= time_ago_in_words(product.updated_at) %></td>

            <!-- <%#= form_for([:active, product]) do |f| %>
              <td>
                <%#= f.check_box :active %>
              </td>
              <td style="font-size:.5em">
                <%#= f.submit%>
              </td>
            <%# end %> -->

            <td>
              <span><%= link_to "X", product, method: :delete, class:"x-btn", data: { confirm: 'Are you sure?' } %></span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div class="col-md-offset-1 col-md-9 white-background">
	<h1>New product</h1>
	<h5>
	<%= link_to 'Back', products_path %>
	</h5>

	<%= render 'form' %>
</div>

app/views/products/show.html.erb
<!-- PRODUCT PICTURE PANE -->
<div class="col-md-5">
  <div id="mid-container" >
      <div class="mid-pic-frame">
        <div id="p-thumbnails-box">
          <% @product.secondary_images.map(&:image).each do |image| %>
            <%= image_tag(image, class: "p-thumbnails") %>
          <% end %>
          
          <%= image_tag(@product.primary_image, class: "p-thumbnails") %>
        </div>
        <img class="img-responsive"  id="product-image" src="<%= image_path(@product.primary_image) %>"/>
      </div>
      <div id="thumbnail-hide">Hide</div>
  </div>
</div>

    
<div class="col-md-5 " >  
  <div class="row grey-border" id="details">
    <div class="col-md-12">
      <div style="margin-bottom:20px;margin-top:15px">
        <a href="/" class="backhome-btn"><div class="glyphicon glyphicon-globe" ></div></a>
        <a class="visible-xs visible-sm pull-right" style="padding-right:15px;" href="mailto:?subject=Take a look at Farallon Co...&amp;body=You should check out this product featured on Farallon Co.: <%= @product.name %> by <%= @product.brand.name %>: <%=request.original_url.html_safe%>" ><%= image_tag("email-message.png", class: "social-show", width: "25") %></a>
      </div>
<!-- SOCIAL HEADER-->
      <div class="row">
        <div class="col-md-12">  
        <div class="centerize hidden-xs hidden-sm">
          <h5 id="social-title" style="margin-top:0px;letter-spacing:2px;font-size:.65em" class="centerize" >SPREAD THE WORD</h5>
            <!-- TWITTER -->
          <a href="http://twitter.com/home?status=Check+out+the+<%= @product.name %>+by+<%= @product.brand.name %>+on+@farallonco+(<%=request.original_url.html_safe%>)" target="blank" ><%= image_tag("twitter.png", id:"fb-social", class: "social-show", width: "25") %>
          </a>
          <!-- FACEBOOK -->
          <a href="http://www.facebook.com/sharer/sharer.php?s=100&p[url]=<%=request.original_url%>&p[images][0]=<%= @product.primary_image.url %>&p[title]=<%= @product.name %>+by+<%= @product.brand.name.html_safe %>+on+Farallon+Co.&p[summary]=Farallon+Co.+-+Top+Tier+Brands,+Fan-Backed+Product,+Join+the+Company." target="blank"><%= image_tag("facebook.png", class: "social-show", width: "20") %></a>
          <!-- TUMBLR -->
          <a href="http://www.tumblr.com/share/photo?source=<%=u @product.primary_image.url %>&caption=<%=u @product.name %>+by+<%=u @product.brand.name %>+on+Farallon+Co.&clickthru=<%=u request.original_url %>" target="blank" ><%= image_tag("tumblr.png", class: "social-show", width: "20") %>
          </a>

          <a href="mailto:?subject=Take a look at Farallon Co...&amp;body=You should check out this product featured on Farallon Co.: <%= @product.name %> by <%= @product.brand.name %>: <%=request.original_url.html_safe%>" ><%= image_tag("email-message.png", class: "social-show", width: "20") %></a>

            <!-- GOOGLE PLUS -->
         <!--  <a href="https://plus.google.com/share?url=<%#=request.original_url.html_safe%>" target="blank"><%#= image_tag("googleplus.png", class: "social-show", width: "20") %></a> -->

          <!-- PINTEREST -->
          <!-- <a href="http://pinterest.com/pin/create/bookmarklet/?media=<%#@product.primary_image%>&url=<%#=request.original_url%>&is_video=false&description=<%#= @product.name %> by <%#=@product.brand.name%> on Farallon Co." target="blank" ><%#= image_tag("pinterest.png", class: "social-show", width: "20") %></a> -->
           
          <!-- STUMBLEUPON -->
          <!-- <a href="http://www.stumbleupon.com/submit?url=<%#=request.original_url%>&title=<%#= @product.brand.name %> by <%#=@product.brand.name%> on Farallon Co.+<%#=request.original_url%>" target="blank"><%#= image_tag("stumbleupon.png", class: "social-show", width: "20") %></a> -->
          <hr class="black-hr" style="padding-bottom:20px;width:60%;">
          </div>
        
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h3 style="margin-top:0px;margin-bottom:-15px;" class="centerize"><%=@product.name.html_safe%></h3>
            <% if current_user.try(:admin?) %>
              <p style="font-size:.55em;margin-bottom:-10px;margin-top:15px;" class="centerize"><%= link_to "[EDIT PRODUCT]",  edit_brand_product_path(@brand, @product)%></p>
            <%end%>
          <br>
          <div class="row">
            <div class="col-md-12">
                <blockquote class="pull-right" style="margin-top:-10px;width:100%">
                  <p style="font-size:1em;font-style:italic;"><%=@product.tasting_notes.html_safe%></p>
                  <h6 style="font-size:.6em"><small><%= @product.brand.founders%> of <%=@product.brand.name.html_safe%></small></h6>
                </blockquote>
            </div>
          </div>
      <div class="row">
        <div class="col-md-12">
          <div class="well well-sm detail-well" style="padding-top:10px;padding-bottom:10px;">
            <div class="row" id="product-details">
              <div class="col-md-7 col-sm-6">
                <h6 class="centerize">Grain Bill</h6>
                <hr class="black-hr" style="margin-top:0">
                <%= @product.grain_bill.html_safe unless @product.grain_bill.blank?%>

                <h6 class="centerize">Hops</h6>
                <hr class="black-hr" style="margin-top:0">
                <%= @product.hops.html_safe unless @product.hops.blank?%>

              </div>
              <div class="col-md-5 col-sm-6">
                <h6 class="centerize">ABV</h6>
                <hr class="black-hr" style="margin-top:0;width:40px">
                <span class="centerize"><%= @product.abv.html_safe unless @product.abv.blank?%>%</span>
                <br>
                <div style="text-align:center;margin-bottom:20px">
                  <h6 class="centerize">IBU</h6>
                  <hr class="black-hr" style="margin-top:0;width:40px;">
                  <%= @product.ibu.html_safe unless @product.ibu.blank?%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
     
          
          <hr class="black-hr">  
          <div class="row">
            <div class="col-md-12">
              <h6 style="margin-bottom:-15px">MEET THE MAKER:</h6>
              <h3><%= link_to @product.brand.name, brand_path(@brand), class:'brand-title' %></h3>
              <% if current_user.try(:admin?) %>
                  <p style="font-size:.55em;margin-bottom:10px;margin-top:-5px"><%= link_to "[EDIT BRAND]", edit_brand_path([@brand])%></p>
              <%end%>
              <h5 class="location" style="font-size:.85em;letter-spacing:1px;" ><%=@product.brand.city.html_safe%>,&nbsp;<%=@product.brand.state.html_safe%></h5>
              
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <%= link_to(@product.brand) do %>
                <%= image_tag(@product.brand.profile_image.image, id: "brand-image") %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row grey-border" style="margin-top:20px;color:black; border-radius:3px;">
      <div class="col-md-12">
        <h6 class="centerize" style="padding-top:10px;">Keep exploring</h6>
        <hr style="margin-top:-1px;width:40% !important;">
          <div class="row">
            <%= render :partial=>'products/product', :collection => @products, :locals => {:size => 'col-md-4 col-xs-6'}  %>
          </div>
          <div class="row">
            <h6 class="centerize" style="padding-top:10px;">More Breweries</h6>
            <hr style="margin-top:-1px;width:40% !important;">
            <%= render :partial=>'brands/brand', :collection => @brands, :locals => {:size => 'col-md-3 col-xs-6'}  %>
          </div>
      </div>
    </div>
    <div class="row" style="height:100px"></div>
</div>





  <!-- END OF DETAILS -->
  <meta property="st:image" content="<%= image_path(@product.primary_image) %>">
  <!-- CELERY SCRIPTS -->
    <script type="text/javascript" src="https://www.trycelery.com/js/celery.js"></script>

<!-- B&B Modal -->
          <div class="modal fade" id="existing-modal" tabindex="-1" role="dialog" aria-labelledby="Submit" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" style="font-size:3em;margin-top:-10px;" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h3 class="modal-title">About the 'Bread & Butter Series'</h3>
                </div>
                <div class="modal-body" >

                  <p style="text-align:center;">This product is part of our 'Bread & Butter' series, which highlights the products that made this brand what it is today or simply new products we think you should be aware of. <br><br>Keep in mind that these are not campaigns. We merely are striving to become your one-stop-shop for product discovery.<br><br><i style="font-size:.7em;">The link below will redirect you to the <%= @product.name %> on our brand partner's site. <br>If you end up purchasing, let us know... We always appreciate a good hat tip.</i></p>
                  <br>
                  <a href="<%= @product.existingurl.html_safe unless @product.existingurl.blank? %>" target="blank">
                    <div class="flatbtn-deux centerize" id="existing-product-btn">Take me there</div>
                  </a>
                </div>
              </div>
            </div>
          </div>